export const membersData = [
  {
    name: "Nittin Madgotara",
    post: "President",
    branch: "Electrical Engg.",
    year: "Finals",
    photo: "nittin.jpg",
    gif: "",
  },
  {
    name: "Shrejal Singh ",
    post: "Vice President",
    branch: "Civil Engg.",
    year: "Finals",
    photo: "shrejal.jpg",
    gif: "",
  },
  {
    name: "Ritesh Madishetty",
    post: "Secretary",
    branch: "Electronics & Comm. Engg.",
    year: "Finals",
    photo: "ritesh.jpg",
    gif: "",
  },
  {
    name: "Nakul Singla",
    post: "Joint Secretary",
    branch: "Electronics & Comm. Engg.",
    year: "Finals",
    photo: "nakul.jpg",
    gif: "",
  },
  {
    name: "Vivek Chaudhary",
    post: "Additional Secretary",
    branch: "Prod. & Industrial Engg.",
    year: "Finals",
    photo: "vivek.jpg",
    gif: "",
  },
  {
    name: "Adityabhan Singh",
    post: "Web Lead",
    branch: "Information Tech.",
    year: "Finals",
    photo: "adityabhan.jpg",
    gif: "",
  },
  {
    name: "Suraj ",
    post: "Web Lead",
    branch: "Prod. & Industrial Engg.",
    year: "Finals",
    photo: "unknown.jpg",
    gif: "",
  },
  {
    name: "Kapil Singh",
    post: "Sponsi Lead",
    branch: "Prod. & Industrial Engg.",
    year: "Finals",
    photo: "unknown.jpg",
    gif: "",
  },
  {
    name: "Chaitanya Rustagi ",
    post: "Sponsi Lead",
    branch: "Prod. & Industrial Engg.",
    year: "Finals",
    photo: "chaitanya.jpg",
    gif: "",
  },
  {
    name: "Nishtha Madaan",
    post: "ML Lead",
    branch: "Mechincal Engg.",
    year: "Finals",
    photo: "nishtha.jpg",
    gif: "",
  },
  {
    name: "Deepak ",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Vitthal Gupta",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Priya",
    post: "Club-Member",
    branch: "Electrical Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Arjit Kedia",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Satyaprakash",
    post: "Club-Member",
    branch: "Prod. & Industrial Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Mayank",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Rudransh",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Khushi Yadav",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Aditya Bhardwaj",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Ujjwal Gupta",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Jagriti Singh",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Hitesh",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Kamakshi Sharma",
    post: "Club-Member",
    branch: "Prod. & Industrial Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Suyash Ranjan",
    post: "Club-Member",
    branch: "Prod. & Industrial Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Riddhi Chauhan",
    post: "Club-Member",
    branch: "Electronics & Comm. Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Mohit Gupta",
    post: "Club-Member",
    branch: "Prod. & Industrial Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Rajeev",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Manish Soni",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Pre-Finals",
    photo: "",
    gif: "",
  },
  {
    name: "Mohit Raturi",
    post: "Club-Member",
    branch: "",
    year: "Pre-Finals",
    photo: "",
    gif: "ME",
  },
  {
    name: "Garvit Gupta",
    post: "Member",
    branch: "Information Technology",
    year: "Sophomores",
    photo:
      "https://i.pinimg.com/originals/b2/e5/c5/b2e5c5c0054c80ee625c2bb172a51bda.jpg",
    gif: "https://orig00.deviantart.net/fd01/f/2018/314/d/8/mars_animation_gif_by_krapey-dcr6foe.gif",
  },
  {
    name: "Neelesh Gupta",
    post: "Club-Member",
    branch: "Electrical Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Rahul Saini",
    post: "Club-Member",
    branch: "Prod. & Industrial Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Jiya Agrawal",
    post: "Club-Member",
    branch: "Electrical Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Diksha dutta",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Bhavya Arya",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Mansi Sarkar",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "suvigya",
    post: "Club-Member",
    branch: "Civil Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Damini",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Chamanlal yadav",
    post: "Club-Member",
    branch: "Civil Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Deepak Saini",
    post: "Club-Member",
    branch: "Civil Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Aditya Aryan",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Udita Saini",
    post: "Club-Member",
    branch: "Electrical Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Sarvagya Agrawal",
    post: "Club-Member",
    branch: "Electrical Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Harsh Taneja",
    post: "Club-Member",
    branch: "Information Tech.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "samarth parkhe",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Harshit",
    post: "Club-Member",
    branch: "Mechincal Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Ujjawal Gupta",
    post: "Club-Member",
    branch: "Electronics & Comm. Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Sheersh Verma",
    post: "Club-Member",
    branch: "Electronics & Comm. Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Kartik Saraswat",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
  {
    name: "Hutashan Sharma",
    post: "Club-Member",
    branch: "Computer Engg.",
    year: "Sophomores",
    photo: "",
    gif: "",
  },
];
